# Configuration file for Nettskjema importer

questions:

  - udf:        'Method used to purify DNA/RNA'
    line:       'Method used to purify DNA / RNA'

  - udf:        'Method used to determine concentration'
    line:       'Method used to determine concentration'

  - udf:        'Sample buffer'
    line:       'Buffer in which samples dissolved'

  - udf:        'Species'
    line:       'Species'

  - udf:        'Reference genome'
    line:       'Reference genome and release version'
    default:    '-- Not provided --'
  
  - udf:        'Project Goal'
    line:       'Project Goal'
  
  - udf:        'Project type'
    line:       'Project type'
    mapping:    'project_type'
  
  - udf:        'REK approval number'
    line:       'REK approval number'
  
  - udf:        'Funded by Norsk Forskningsradet'
    line:       'Is project fully or partly funded by The Research Council of Norway (NFR)?'
    transform:  'yes_no_bool'

  - udf:        'Evaluation type'
    line:       'Are the samples ready to sequence'
    mapping:    'evaluation_type'

  - udf:        'Library prep used'
    line:       'If yes, please state which kit / method you used'

  - udf:        'Sample prep requested'
    default:    'None'

  - udf:        'Sample prep requested'
    line:       'For DNA samples'
    
  - udf:        'Sample prep requested'
    line:       'For RNA samples'

  - udf:        'Sequencing instrument requested'
    line:       'Sequencing Instrument requested'

  - udf:        'Read length requested'
    line:       'Choose run length'
    transform:  'get_read_length'

  - udf:        'Read length requested'
    line:       'Choose run type'
    transform:  'get_read_length'

  - udf:        'Total # of lanes requested'
    line:       'Total number of runs requested'

  - udf:        'Delivery method'
    line:       'Data delivery'
    mapping:    'delivery_method'
    
  - udf:        'Delivery method'
    line:       'Data delivery'
    mapping:    'delivery_method'
    
  - udf:        'Delivery method'
    line:       'Select hard drive'
    mapping:    'delivery_method2_hdd'

  - udf:        'NeLS project identifier'
    line:       'Existing NeLS project ID'

  - udf:        'TODO'
    line:       'TSD project ID (e.g. pXX)'

  - udf:        'Bioinformatic services'
    line:       'Do you want to use our bioinformatic analysis service?'
    transform:  'yes_no_bool'

  - udf:        'Contact person'
    line:       'Contact Name'

  - udf:        'Contact email'
    line:       'Contact Email'

  - udf:        'Contact telephone'
    line:       'Contact Telephone'

  - udf:        'Contact institution'
    line:       'Contact Institution'

  - udf:        'Billing contact person'
    line:       'Billing contact person'

  - udf:        'Billing email'
    line:       'Billing Email'

  - udf:        'Billing telephone'
    line:       'Billing Telephone'

  - udf:        'Billing institution'
    line:       'Billing institution and full billing address'
    transform:  'first_line'

  - udf:        'Billing address'
    line:       'Billing institution and full billing address'
    transform:  'skip_first_line'

  - udf:        'Purchase order number'
    line:       'Purchase Order Number'

  - udf:        'Kontostreng (Internal orders only)'
    line:       'Kontostreng (Koststed-Prosjekt-Kilde)'

  - udf:        'TODO'
    line:       'Institution VAT number'

  - udf:        'Sample type'
    default:    '-- Not provided --'

  - udf:        'Prepaid account'
    default:    'No'

  - udf:        'Date samples received'
    transform:  'todays_date'
    default:    'placeholder'