project_fields:
  "Project type": "FHI-Covid19"
  "Evaluation type": "Prep"
  "Contact email": "Ignacio.GarciaLlorente@fhi.no; Kathrine.Stene-Johansen@fhi.no; Karoline.Bragstad@fhi.no"
  "Contact person":  "FHI"
  "Contact institution": "FHI"
  "Delivery method": "FHI-Covid19"

sample_fields: 

workflow: "Covid NimaGen EasySeq"

tasks:
  - "ReadFHISampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"

project_name_placeholder: "{:%Y%m%d}-N"