project_fields:
  "Project type": "FHI-Covid19"
  "Sample type": "TODO"
  "Evaluation type": "Prep"
  "Sample prep requested": "Swift SNAP"
  "Contact email": "TODO"
  "Contact person":  "TODO"
  "Contact institution": "FHI"
  "Delivery method": "FHI-Covid19"

sample_fields: 
  "Sample prep NSC": "Swift SNAP"

workflow: "NSC 16S 8.0"

tasks:
  - "ReadFHISampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"