project_fields:
  "Project type": "FHI-Covid19"
  "Evaluation type": "Prep"
  "Sample prep requested": "Swift SNAP"
  "Contact email": "TODO"
  "Contact person":  "TODO"
  "Contact institution": "FHI"
  "Delivery method": "FHI-Covid19"

sample_fields: 

workflow: "Covid Swift SNAP"

tasks:
  - "ReadFHISampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"

project_name_placeholder: "{:%Y%m%d}-S"