project_fields:
  "Project type": "MIK-Covid19"
  "Evaluation type": "Prep"
  "Contact email": "mik_covidseq_nsc@ous-hf.no; Ignacio.GarciaLlorente@fhi.no; Kathrine.Stene-Johansen@fhi.no; Karoline.Bragstad@fhi.no; Jon.Brate@fhi.no"
  "Contact person":  "MIK"
  "Contact institution": "OUS"
  "Delivery method": "MIK-Covid19"

sample_fields: 

workflow: "Covid NimaGen EasySeq"

tasks:
  - "ReadMIKSampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"

project_name_placeholder: "{:%Y%m%d}-N"