project_fields:
  "Project type": "MIK-Covid19"
  "Sample type": "TODO"
  "Evaluation type": "Prep"
  "Sample prep requested": "Swift SNAP"
  "Contact email": "TODO"
  "Contact person":  "MIK"
  "Contact institution": "OUS"
  "Delivery method": "MIK-Covid19"

sample_fields: 

workflow: "Covid Swift SNAP"

tasks:
  - "ReadMIKSampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"

project_name_placeholder: "Covid-xx-Swift-MIK"
