project_fields:
  "Project type": "MIK-Covid19"
  "Evaluation type": "Prep"
  "Contact email": "UXMOLB@ous-hf.no; fmuller@ous-hf.no; regbar@ous-hf.no; cflad@ous-hf.no; nimari@ous-hf.no; UXISES@ous-hf.no; UXLNDR@ous-hf.no"
  "Contact person":  "MIK"
  "Contact institution": "OUS"
  "Delivery method": "MIK-Covid19"

sample_fields: 

workflow: "Covid NimaGen EasySeq"

tasks:
  - "ReadMIKSampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"

project_name_placeholder: "{:%Y%m%d}-N"